services:
  api:
    image: ${REGISTRY:-ms-openai-cosmosdb}/chat-service-api:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./ChatServiceWebApi/Dockerfile
    ports:
    - "80:80"
    environment:
      DOTNET_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      AllowedHosts: '*'
      MSCosmosDBOpenAI__CognitiveSearch__IndexName: 'vector-index'
      MSCosmosDBOpenAI__CognitiveSearch__MaxVectorSearchResults: '10'
      MSCosmosDBOpenAI__CognitiveSearch__Endpoint: 'https://oed5tfwrpneay-cog-search.search.windows.net/'
      MSCosmosDBOpenAI__CognitiveSearch__Key: '1dATmJVRiJ4HoZlHs5v2DjoQmRqQE3yOfHbPU5eoNOAzSeD8NmlA'
      MSCosmosDBOpenAI__OpenAI__CompletionsDeployment: 'completions'
      MSCosmosDBOpenAI__OpenAI__EmbeddingsDeployment: 'embeddings'
      MSCosmosDBOpenAI__OpenAI__MaxConversationBytes: '2000'
      MSCosmosDBOpenAI__OpenAI__Endpoint: 'https://oed5tfwrpneay-openai.openai.azure.com/'
      MSCosmosDBOpenAI__OpenAI__Key: '1dc8f09a6caf44b0b5312632fedaea07'
      MSCosmosDBOpenAI__CosmosDB__Containers: 'completions, customer, product'
      MSCosmosDBOpenAI__CosmosDB__Database: 'database'
      MSCosmosDBOpenAI__CosmosDB__Endpoint: 'https://oed5tfwrpneay-cosmos-nosql.documents.azure.com:443/'
      MSCosmosDBOpenAI__CosmosDB__Key: '1DSBN9LUoY5NGu58oNIt7Z1CPxOkeXKzmcxNLpuOvW4cxFwcTYkqXQ3xcObrpQMcwptnAPnNg4bEACDbYxMmFA=='
      MSCosmosDBOpenAI__DurableSystemPrompt__BlobStorageContainer: 'system-prompt'
      MSCosmosDBOpenAI__DurableSystemPrompt__BlobStorageConnection: 'DefaultEndpointsProtocol=https;AccountName=oed5tfwrpneaypromptsa;AccountKey=Phbf5yMSGzGWiMxiB98AxUhmKpzuXU22pMs2AzeZOwvvsiqe5tOwt6oTs7H4z6DRnCSj49pRdVxt+AStsVohXQ==;EndpointSuffix=core.windows.net'
      MSCosmosDBOpenAI__SystemPromptName: 'RetailAssistant.Default'
      Logging__Loglevel__Default: 'Debug'
      Logging__Loglevel__Microsoft__AspNetCore: 'Debug'
  web:
    image: ${REGISTRY:-ms-openai-cosmosdb}/chat-web-app:${TAG:-latest}
    build:
      context: ./
      dockerfile: ./Search/Dockerfile
    ports:
    - "8080:80"
    environment:
      DOTNET_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      AllowedHosts: '*'
      DetailedErrors: 'true'
      MSCosmosDBOpenAI__ChatManager__APIUrl: "http://api:80"
      MSCosmosDBOpenAI__ChatManager__APIRoutePrefix: ""
      Logging__Loglevel__Default: 'Debug'
      Logging__Loglevel__Microsoft__AspNetCore: 'Debug'
